spring:
  datasource:
    password: Tushar@123
    url: jdbc:mysql:///todo
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: ToDo-Service

  mail:
    host: smtp.gmail.com
    port: 587
    username: tusharjaiwal123@gmail.com
    password: pswi tdyj tkcm vofa
    properties:
      mail:
        smtp:
          auth: true
          starttls:

            enable: true
        debug: true
  sql:
    init:
      mode: always

server:
  port: 9001


